// Code generated by goctl. DO NOT EDIT!
// Source: aitools.proto

package server

import (
	"context"

	"db_ai/service/aitools/rpc/internal/logic"
	"db_ai/service/aitools/rpc/internal/svc"
	"db_ai/service/aitools/rpc/types/aitools"
)

type AiToolsRpcServer struct {
	svcCtx *svc.ServiceContext
	aitools.UnimplementedAiToolsRpcServer
}

func NewAiToolsRpcServer(svcCtx *svc.ServiceContext) *AiToolsRpcServer {
	return &AiToolsRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *AiToolsRpcServer) SayHello(ctx context.Context, in *aitools.SayHelloReq) (*aitools.SayHelloResp, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}

func (s *AiToolsRpcServer) RemoteCommand(ctx context.Context, in *aitools.RemoteCommandReq) (*aitools.RemoteCommandResp, error) {
	l := logic.NewRemoteCommandLogic(ctx, s.svcCtx)
	return l.RemoteCommand(in)
}
