// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	aitools "db_ai/service/aitools/api/internal/handler/aitools"
	"db_ai/service/aitools/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/aitools/getbackuplogbyhosts",
				Handler: aitools.GetbackuplogbyhostsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"), rest.WithTimeout(300000*time.Millisecond),
	)
}
