// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: aitools.proto

package aitools

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SayHelloReq) Reset() {
	*x = SayHelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aitools_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloReq) ProtoMessage() {}

func (x *SayHelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_aitools_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloReq.ProtoReflect.Descriptor instead.
func (*SayHelloReq) Descriptor() ([]byte, []int) {
	return file_aitools_proto_rawDescGZIP(), []int{0}
}

type SayHelloResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *SayHelloResp) Reset() {
	*x = SayHelloResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aitools_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResp) ProtoMessage() {}

func (x *SayHelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_aitools_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResp.ProtoReflect.Descriptor instead.
func (*SayHelloResp) Descriptor() ([]byte, []int) {
	return file_aitools_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type RemoteCommandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Commands string `protobuf:"bytes,3,opt,name=commands,proto3" json:"commands,omitempty"`
}

func (x *RemoteCommandReq) Reset() {
	*x = RemoteCommandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aitools_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteCommandReq) ProtoMessage() {}

func (x *RemoteCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_aitools_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteCommandReq.ProtoReflect.Descriptor instead.
func (*RemoteCommandReq) Descriptor() ([]byte, []int) {
	return file_aitools_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteCommandReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RemoteCommandReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RemoteCommandReq) GetCommands() string {
	if x != nil {
		return x.Commands
	}
	return ""
}

type RemoteCommandResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Status int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoteCommandResp) Reset() {
	*x = RemoteCommandResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aitools_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteCommandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteCommandResp) ProtoMessage() {}

func (x *RemoteCommandResp) ProtoReflect() protoreflect.Message {
	mi := &file_aitools_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteCommandResp.ProtoReflect.Descriptor instead.
func (*RemoteCommandResp) Descriptor() ([]byte, []int) {
	return file_aitools_proto_rawDescGZIP(), []int{3}
}

func (x *RemoteCommandResp) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RemoteCommandResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_aitools_proto protoreflect.FileDescriptor

var file_aitools_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x61, 0x79, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x61, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x56, 0x0a, 0x10, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x22, 0x43, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x8e, 0x01, 0x0a, 0x0b, 0x41, 0x69, 0x54,
	0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x12, 0x37, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x14, 0x2e, 0x61, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x53,
	0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x69, 0x74,
	0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x46, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x19, 0x2e, 0x61, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x61, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x61,
	0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aitools_proto_rawDescOnce sync.Once
	file_aitools_proto_rawDescData = file_aitools_proto_rawDesc
)

func file_aitools_proto_rawDescGZIP() []byte {
	file_aitools_proto_rawDescOnce.Do(func() {
		file_aitools_proto_rawDescData = protoimpl.X.CompressGZIP(file_aitools_proto_rawDescData)
	})
	return file_aitools_proto_rawDescData
}

var file_aitools_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aitools_proto_goTypes = []interface{}{
	(*SayHelloReq)(nil),       // 0: aitools.SayHelloReq
	(*SayHelloResp)(nil),      // 1: aitools.SayHelloResp
	(*RemoteCommandReq)(nil),  // 2: aitools.RemoteCommandReq
	(*RemoteCommandResp)(nil), // 3: aitools.RemoteCommandResp
}
var file_aitools_proto_depIdxs = []int32{
	0, // 0: aitools.AiTools_rpc.SayHello:input_type -> aitools.SayHelloReq
	2, // 1: aitools.AiTools_rpc.RemoteCommand:input_type -> aitools.RemoteCommandReq
	1, // 2: aitools.AiTools_rpc.SayHello:output_type -> aitools.SayHelloResp
	3, // 3: aitools.AiTools_rpc.RemoteCommand:output_type -> aitools.RemoteCommandResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aitools_proto_init() }
func file_aitools_proto_init() {
	if File_aitools_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aitools_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aitools_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aitools_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteCommandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aitools_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteCommandResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aitools_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aitools_proto_goTypes,
		DependencyIndexes: file_aitools_proto_depIdxs,
		MessageInfos:      file_aitools_proto_msgTypes,
	}.Build()
	File_aitools_proto = out.File
	file_aitools_proto_rawDesc = nil
	file_aitools_proto_goTypes = nil
	file_aitools_proto_depIdxs = nil
}
