// Code generated by goctl. DO NOT EDIT.
package types

type RemoteCommandReq struct {
	HostIps string `json:"host_ips,omitempty"`
}

type RemoteCommandRespData struct {
	HostIp string `json:"host_ip"`
	Output string `json:"output,omitempty"`
}

type RemoteCommandResp struct {
	Successful bool                  `json:"successful,omitempty"`
	Data       RemoteCommandRespData `json:"data"`
}
